def get_products():
    return [
        {
            'sku': 'TX-1000',
            'name': 'Silk Print',
            'category': 'silk',
            'image': '/products/tx-1000.svg',
            'fabric': 'Silk',
            'color': 'Lavender',
            'material': 'Silk Blend',
            'gsm': 120,
            'stock': 142,
            'price': 18.5,
        },
        {
            'sku': 'TX-1001',
            'name': 'Cotton Yard',
            'category': 'cotton',
            'image': '/products/tx-1001.svg',
            'fabric': 'Cotton',
            'color': 'Ivory',
            'material': '100% Cotton',
            'gsm': 160,
            'stock': 550,
            'price': 8.75,
        },
        {
            'sku': 'TX-1002',
            'name': 'Denim Roll',
            'category': 'shirts',
            'image': '/products/tx-1002.svg',
            'fabric': 'Denim',
            'color': 'Indigo',
            'material': 'Heavy Cotton',
            'gsm': 340,
            'stock': 96,
            'price': 27.25,
        },
        {
            'sku': 'TX-1003',
            'name': 'Linen Sheet',
            'category': 'saree',
            'image': '/products/tx-1003.svg',
            'fabric': 'Linen',
            'color': 'Sand',
            'material': 'Linen',
            'gsm': 200,
            'stock': 210,
            'price': 12.0,
        },
        {
            'sku': 'TX-1004',
            'name': 'Polyester Weave',
            'category': 'polyester',
            'image': '/products/tx-1004.svg',
            'fabric': 'Polyester',
            'color': 'Pearl',
            'material': 'Polyester',
            'gsm': 150,
            'stock': 320,
            'price': 9.5,
        },
    ]
